### ISSUE TITLE
Just want to say thanks for the maintenance and long polling option

### ISSUE THREAD

**Issue by pherris** [ruby-shoryuken/shoryuken#498]
Much appreciated!

![sqs_management_console](https://user-images.githubusercontent.com/2084598/39527950-6602fa7c-4de8-11e8-8aac-770f106ee3fd.png)

**Comment by phstc** [comment]
Thanks @pherris. I really appreciated the feedback 😍

**Comment by smostovoy** [comment]
Since this thread is open I'll tell it here - Thank you, Pablo, for maintenance!
