### ISSUE TITLE
--rails unsupport Rails 6.0.2.1 

### ISSUE THREAD

**Issue by cofemei** [ruby-shoryuken/shoryuken#594]
My case

Rails 6.0.2.1
Ruby 2.7.0

only --rails get **No worker found for** 
> $ bundle exec shoryuken -C ./config/shoryuken.yml --rails                                     
> 2020-02-13T01:14:58Z 28319 TID-53w WARN: DEPRECATION WARNING: Using I18n fallbacks with an empty `defaults` sets the defaults to include the `default_locale`. This behavior will change in Rails 6.1. If you desire the default locale to be included in the defaults, please explicitly configure it with `config.i18n.fallbacks.defaults = [I18n.default_locale]` or `config.i18n.fallbacks = [I18n.default_locale, {...}]`. If you want to opt-in to the new behavior, use `config.i18n.fallbacks.defaults = [nil, {...}]`. (called from <main> at /Users/mei/Dropbox/athena/athena-backend/config/environment.rb:5)
> 2020-02-13T01:14:58Z 28319 TID-53w INFO: Starting
> 2020-02-13T01:14:58Z 28319 TID-53w DEBUG: Firing 'startup' lifecycle event
> 2020-02-13T01:14:58Z 28319 TID-des DEBUG: Firing 'dispatch' lifecycle event
> 2020-02-13T01:14:58Z 28319 TID-des DEBUG: Ready: 25, Busy: 0, Active Queues: [["athena_lab.fifo", 1]]
> 2020-02-13T01:14:58Z 28319 TID-des DEBUG: Looking for new messages in athena_lab.fifo
> 2020-02-13T01:15:15Z 28319 TID-des DEBUG: Found 1 messages for athena_lab.fifo
> 2020-02-13T01:15:15Z 28319 TID-des DEBUG: Fetcher for athena_lab.fifo completed in 16925.933 ms
> 2020-02-13T01:15:15Z 28319 TID-des DEBUG: Assigning ee9b44db-245b-4655-a092-ee9f0b7213d3
> 2020-02-13T01:15:15Z 28319 TID-e0g ERROR: No worker found for athena_lab.fifo
> 2020-02-13T01:15:15Z 28319 TID-e10 DEBUG: Firing 'dispatch' lifecycle event
> 2020-02-13T01:15:15Z 28319 TID-e10 DEBUG: Ready: 25, Busy: 0, Active Queues: [["athena_lab.fifo", 1]]
> 2020-02-13T01:15:15Z 28319 TID-e10 DEBUG: Looking for new messages in athena_lab.fifo
> 

-r ./app/jobs Just work 
> $ bundle exec shoryuken -C ./config/shoryuken.yml -r ./app/jobs --rails
> 2020-02-13T01:12:04Z 28180 TID-53w WARN: DEPRECATION WARNING: Using I18n fallbacks with an empty `defaults` sets the defaults to include the `default_locale`. This behavior will change in Rails 6.1. If you desire the default locale to be included in the defaults, please explicitly configure it with `config.i18n.fallbacks.defaults = [I18n.default_locale]` or `config.i18n.fallbacks = [I18n.default_locale, {...}]`. If you want to opt-in to the new behavior, use `config.i18n.fallbacks.defaults = [nil, {...}]`. (called from <main> at /Users/mei/Dropbox/athena/athena-backend/config/environment.rb:5)
> 2020-02-13T01:12:05Z 28180 TID-53w INFO: Starting
> 2020-02-13T01:12:05Z 28180 TID-53w DEBUG: Firing 'startup' lifecycle event
> 2020-02-13T01:12:05Z 28180 TID-dfc DEBUG: Firing 'dispatch' lifecycle event
> 2020-02-13T01:12:05Z 28180 TID-dfc DEBUG: Ready: 25, Busy: 0, Active Queues: [["athena_lab.fifo", 1]]
> 2020-02-13T01:12:05Z 28180 TID-dfc DEBUG: Looking for new messages in athena_lab.fifo
> 2020-02-13T01:12:25Z 28180 TID-dfc DEBUG: Fetcher for athena_lab.fifo completed in 20156.988999999998 ms
> 2020-02-13T01:12:25Z 28180 TID-dfc DEBUG: Paused athena_lab.fifo
> 2020-02-13T01:12:25Z 28180 TID-e10 DEBUG: Unpaused athena_lab.fifo
> 2020-02-13T01:12:25Z 28180 TID-e10 DEBUG: Firing 'dispatch' lifecycle event
> 2020-02-13T01:12:25Z 28180 TID-e10 DEBUG: Ready: 25, Busy: 0, Active Queues: [["athena_lab.fifo", 1]]
> 2020-02-13T01:12:25Z 28180 TID-e10 DEBUG: Looking for new messages in athena_lab.fifo
> 2020-02-13T01:12:45Z 28180 TID-e10 DEBUG: Fetcher for athena_lab.fifo completed in 20072.302 ms
> 2020-02-13T01:12:45Z 28180 TID-e10 DEBUG: Paused athena_lab.fifo
> 2020-02-13T01:12:45Z 28180 TID-dfc DEBUG: Unpaused athena_lab.fifo
> 2020-02-13T01:12:45Z 28180 TID-dfc DEBUG: Firing 'dispatch' lifecycle event
> 2020-02-13T01:12:45Z 28180 TID-dfc DEBUG: Ready: 25, Busy: 0, Active Queues: [["athena_lab.fifo", 1]]
>

**Comment by phstc** [comment]
Hi @cofemei 

It seems that your Rails env is not auto-loading `app/jobs`. 

Can you check if `app/jobs` is in your auto-load path? 

```ruby
Rails.application.configure do
  config.autoload_paths << "#{Rails.root}/app/jobs"
end
```

**Comment by cofemei** [comment]
I moidfy app/jobs is in  auto-load path

Same behavior ```No worker found for athena_lab.fifo```

```RUBY
# config/application.rb

# frozen_string_literal: true
require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)

module AthenaBackend
  class Application < Rails::Application
    config.load_defaults 6.0

    # config.autoload_paths += ["#{config.root}/app/services"]
    config.autoload_paths << "#{config.root}/app/jobs"
    config.active_job.queue_adapter = :shoryuken

    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource '*', headers: :any, methods: %i[get post options]
      end
    end
    config.exceptions_app = self.routes
  end
end
```


```BASH
bundle exec shoryuken --rails -C ./config/shoryuken.yml                          
2020-02-13T02:40:39Z 34342 TID-53w WARN: DEPRECATION WARNING: Using I18n fallbacks with an empty `defaults` sets the defaults to include the `default_locale`. This behavior will change in Rails 6.1. If you desire the default locale to be included in the defaults, please explicitly configure it with `config.i18n.fallbacks.defaults = [I18n.default_locale]` or `config.i18n.fallbacks = [I18n.default_locale, {...}]`. If you want to opt-in to the new behavior, use `config.i18n.fallbacks.defaults = [nil, {...}]`. (called from <main> at /Users/mei/Dropbox/athena/athena-backend/config/environment.rb:5)
2020-02-13T02:40:39Z 34342 TID-53w INFO: Starting
2020-02-13T02:40:39Z 34342 TID-53w DEBUG: Firing 'startup' lifecycle event
2020-02-13T02:40:39Z 34342 TID-d8o DEBUG: Firing 'dispatch' lifecycle event
2020-02-13T02:40:39Z 34342 TID-d8o DEBUG: Ready: 25, Busy: 0, Active Queues: [["athena_lab.fifo", 1]]
2020-02-13T02:40:39Z 34342 TID-d8o DEBUG: Looking for new messages in athena_lab.fifo
2020-02-13T02:40:40Z 34342 TID-d8o DEBUG: Found 1 messages for athena_lab.fifo
2020-02-13T02:40:40Z 34342 TID-d8o DEBUG: Fetcher for athena_lab.fifo completed in 127.311 ms
2020-02-13T02:40:40Z 34342 TID-d8o DEBUG: Assigning aa8e8203-5a59-4d2a-9916-2bce2d7c6486
2020-02-13T02:40:40Z 34342 TID-duc ERROR: No worker found for athena_lab.fifo
2020-02-13T02:40:40Z 34342 TID-duw DEBUG: Firing 'dispatch' lifecycle event
2020-02-13T02:40:40Z 34342 TID-duw DEBUG: Ready: 24, Busy: 1, Active Queues: [["athena_lab.fifo", 1]]
2020-02-13T02:40:40Z 34342 TID-duw DEBUG: Looking for new messages in athena_lab.fifo
^C2020-02-13T02:40:44Z 34342 TID-53w DEBUG: Got INT signal
2020-02-13T02:40:44Z 34342 TID-53w INFO: Received INT, will shutdown
2020-02-13T02:40:44Z 34342 TID-53w INFO: Shutting down
2020-02-13T02:40:44Z 34342 TID-53w DEBUG: Firing 'shutdown' lifecycle event
```

**Comment by phstc** [comment]
@cofemei could you also share how you are configuring your worker to consume from `athena_lab.fifo` ([robably with `queue_as`)?

**Comment by cofemei** [comment]
```RUBY
# app/jobs/two_job.rb
class TwoJob < ApplicationJob

  queue_as 'athena_lab.fifo'

  def perform(name)
    puts "TwoJob say Hello, #{name}"
    p Product.find(name)
    # all success, delete message
    # sqs_msg.delete
  end

end
```

**Comment by phstc** [comment]
@cofemei could you share your `shoryuken.yml`?

**Comment by cofemei** [comment]
./config/shoryuken.yml
```YML
concurrency: <%= ENV['WORKER_CONCURRENCY'] || 25 %>
delay: 0
queues:
  - ['athena_lab.fifo', 1]
```

**Comment by phstc** [comment]
Your setup looks correct. The only thing that comes to mind is that Rails is not auto-loading your jobs. But I couldn't reproduce it. Can you share your project code? It may be something specific to your setup. 

` -r ./app/jobs --rails` should be ok to use too.

**Comment by cofemei** [comment]
Simple code

https://github.com/cofemei/shoryuken_594

`-r ./app/jobs --rails` Only work on Shoryuken Jobs

**Comment by celsocrivelaro** [comment]
Same issue with Ruby 2.6.5 and Rails 6.0

`$ bundle exec shoryuken -q exercise-return -r ./app/workers/ --rails                                                                                                                           ‹ruby-2.6.5›
Traceback (most recent call last):
	12: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	11: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	10: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/bin/shoryuken:23:in `<main>'
	 9: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/bin/shoryuken:23:in `load'
	 8: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/shoryuken-5.0.4/bin/shoryuken:53:in `<top (required)>'
	 7: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	 6: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 5: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 4: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 3: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/shoryuken-5.0.4/bin/shoryuken:42:in `start'
	 2: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/shoryuken-5.0.4/lib/shoryuken/runner.rb:39:in `run'
	 1: from /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/shoryuken-5.0.4/lib/shoryuken/environment_loader.rb:30:in `load'
/Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/shoryuken-5.0.4/lib/shoryuken/environment_loader.rb:156:in `validate_queues': The specified queue(s) exercise-return do not exist. (ArgumentError)
Try 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings`

**Comment by phstc** [comment]
@celsocrivelaro 

Can you confirm, this `bundle exec shoryuken -q exercise-return -r ./app/workers/ --rails` fails and this `bundle exec shoryuken -q exercise-return -r ./app/workers/` works?

The error above

> /Users/crivelaro/.rvm/gems/ruby-2.6.5/gems/shoryuken-5.0.4/lib/shoryuken/environment_loader.rb:156:in `validate_queues': The specified queue(s) exercise-return do not exist. (ArgumentError)
Try 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings

is about a missing queue.

It is probably new with Rails 6 loading. Sidekiq handles that differently https://github.com/mperham/sidekiq/blob/ccc71d18a23250f813ba6835f8d4eeba298696b4/lib/sidekiq/cli.rb#L251

**Comment by celsocrivelaro** [comment]
@phstc The queue is there:

```bash
$ bundle exec shoryuken sqs ls                                                                                                                                                                 ‹ruby-2.6.5›
Queue              Messages Available    Messages Inflight    Last Modified
exercise-return    4                     0                    2020-02-24 21:36:51 -0300
hello              0                     0                    2020-02-25 19:00:48 -0300
```

`bundle exec shoryuken -q exercise-return -r ./app/workers/result_worker.rb` works fine. 

```bash
$ bundle exec shoryuken -q exercise-return -r ./app/workers/result_worker.rb                                                                                                                   ‹ruby-2.6.5›
2020-02-25T22:40:40Z 60399 TID-ow3elvmf8 INFO: Starting
2020-02-25T22:40:40Z 60399 TID-ow3eojxn8 ResultWorker/exercise-return/a2ff7e85-eee4-4308-8a90-554c64cc6ebb INFO: started at 2020-02-25 19:40:40 -0300
2020-02-25T22:40:40Z 60399 TID-ow3eojxn8 ResultWorker/exercise-return/a2ff7e85-eee4-4308-8a90-554c64cc6ebb INFO: failed in: 0.532 ms
2020-02-25T22:40:40Z 60399 TID-ow3em8cxc ResultWorker/exercise-return/4c7a2dc3-dc5e-4a3b-a5c3-81fc2e3dbf0d INFO: started at 2020-02-25 19:40:40 -0300
2020-02-25T22:40:40Z 60399 TID-ow3em8cxc ResultWorker/exercise-return/4c7a2dc3-dc5e-4a3b-a5c3-81fc2e3dbf0d INFO: failed in: 5.479 ms
```

**Comment by odineiramone** [comment]
Hello @phstc!

I'm running at the same problem right now. Do you have any news about it?

Thanks!

**Comment by phstc** [comment]
@odineiramone no news. I don't have any projects running on Rails 6.x. `-r ./app/jobs` that should have worked if your workers are in there.

I need contributors for adding Rails 6 compatibility. Any volunteers? 

Checking [sidekiq](https://github.com/mperham/sidekiq/blob/master/Changes.md#60) it seems there are some other good stuff with Rails 6, it seems that now we can pass Active Job adapter specific options, and that's something that other people asked for, for example, for using Shoryuken middleware with Rails.

**Comment by rkiller** [comment]
Running Rails 6.0.3.4
Ruby 2.6.6

Getting the No worker found message sometimes:


2020-11-02T18:59:41.034-08:00 | 2020-11-03T02:59:40Z 25761 TID-wlfts DEBUG: Ready: 25, Busy: 0, Active Queues: [["sqs_global_queue_development", 1]]
-- | --
  | 2020-11-02T18:59:41.035-08:00 | 2020-11-03T02:59:40Z 25761 TID-wlfts DEBUG: Looking for new messages in sqs_global_queue_development
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-wlfts DEBUG: Found 1 messages for sqs_global_queue_development
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-wlfts DEBUG: Fetcher for sqs_global_queue_development completed in 19194.124366 ms
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-wlfts DEBUG: Assigning 7af20873-5c12-4421-a250-5c2524233ea8
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-1jw0oo ERROR: No worker found for sqs_global_queue_development
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-15rwws DEBUG: Unpaused sqs_mail_queue_development
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-15rwws DEBUG: Firing 'dispatch' lifecycle event
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-15rwws DEBUG: Ready: 25, Busy: 0, Active Queues: [["sqs_mail_queue_development", 1], ["sqs_global_queue_development", 1]]
  | 2020-11-02T19:00:01.041-08:00 | 2020-11-03T03:00:00Z 25761 TID-15rwws DEBUG: Looking for new messages in sqs_global_queue_development
  | 2020-11-02T19:00:21.066-08:00 | 2020-11-03T03:00:20Z 25761 TID-15rwws DEBUG: Fetcher for sqs_global_queue_development completed in 20004.102584 ms
  | 2020-11-02T19:00:21.066-08:00 | 2020-11-03T03:00:20Z 25761 TID-15rwws DEBUG: Paused sqs_global_queue_development

However, it works about 95% of the time. Not sure of the issue.

**Comment by rkiller** [comment]
<img width="1386" alt="Screen Shot 2020-11-02 at 7 16 22 PM" src="https://user-images.githubusercontent.com/4185175/97946653-ef4edc00-1d3f-11eb-81ea-6ec3d8c5533e.png">

**Comment by cjlarose** [comment]
@cofemei I forked your repo (https://github.com/cjlarose/shoryuken_594/tree/b83ca505f933b9e005e1e124c49caacf14ead527) and found that I'm able to consume ActiveJob jobs as expected.

The changes I had to make were to specify the `:shoryuken` adapter in `config/application.rb`

```ruby
    config.active_job.queue_adapter = :shoryuken
```

and to enqueue the job using `#perform_later`.

```ruby
GuestsCleanupJob.perform_later 1, 2, 3
```

I started the `shoryuken` worker

```sh
bundle exec shoryuken -C config/shoryuken.yml --rails
```

...and was able to observe that the worker ran as expected.

```
2021-03-03T06:43:59Z 76932 TID-chg ActiveJob/GuestsCleanupJob/cjlarose_shoryuken_test.fifo/8b67661b-8d02-48d1-b88f-f4d6ed5a93ca INFO: Performing GuestsCleanupJob (Job ID: 4
cc40b94-0292-4da1-9acd-465adceb292c) from Async(cjlarose_shoryuken_test.fifo) enqueued at 2021-03-03T06:43:58Z with arguments: 1, 2, 3
[1, 2, 3]
2021-03-03T06:43:59Z 76932 TID-chg ActiveJob/GuestsCleanupJob/cjlarose_shoryuken_test.fifo/8b67661b-8d02-48d1-b88f-f4d6ed5a93ca INFO: Performed GuestsCleanupJob (Job ID: 4c
c40b94-0292-4da1-9acd-465adceb292c) from Async(cjlarose_shoryuken_test.fifo) in 0.06ms
2021-03-03T06:43:59Z 76932 TID-chg ActiveJob/GuestsCleanupJob/cjlarose_shoryuken_test.fifo/8b67661b-8d02-48d1-b88f-f4d6ed5a93ca INFO: completed in: 437.565 ms
```

I think the problem might have been with the way you were enqueuing the message into SQS. Were you using `#perform_later`?

**Comment by cjlarose** [comment]
> I need contributors for adding Rails 6 compatibility. Any volunteers?

Since @phstc wrote this, we're now testing against Rails 6.x explicitly in CI and everything so far indicates that it works as expected.

**Comment by cofemei** [comment]
> @cofemei I forked your repo (https://github.com/cjlarose/shoryuken_594/tree/b83ca505f933b9e005e1e124c49caacf14ead527) and found that I'm able to consume ActiveJob jobs as expected.
> 
> The changes I had to make were to specify the `:shoryuken` adapter in `config/application.rb`
> 
> ```ruby
>     config.active_job.queue_adapter = :shoryuken
> ```
> 
> and to enqueue the job using `#perform_later`.
> 
> ```ruby
> GuestsCleanupJob.perform_later 1, 2, 3
> ```
> 
> I started the `shoryuken` worker
> 
> ```shell
> bundle exec shoryuken -C config/shoryuken.yml --rails
> ```
> 
> ...and was able to observe that the worker ran as expected.
> 
> ```
> 2021-03-03T06:43:59Z 76932 TID-chg ActiveJob/GuestsCleanupJob/cjlarose_shoryuken_test.fifo/8b67661b-8d02-48d1-b88f-f4d6ed5a93ca INFO: Performing GuestsCleanupJob (Job ID: 4
> cc40b94-0292-4da1-9acd-465adceb292c) from Async(cjlarose_shoryuken_test.fifo) enqueued at 2021-03-03T06:43:58Z with arguments: 1, 2, 3
> [1, 2, 3]
> 2021-03-03T06:43:59Z 76932 TID-chg ActiveJob/GuestsCleanupJob/cjlarose_shoryuken_test.fifo/8b67661b-8d02-48d1-b88f-f4d6ed5a93ca INFO: Performed GuestsCleanupJob (Job ID: 4c
> c40b94-0292-4da1-9acd-465adceb292c) from Async(cjlarose_shoryuken_test.fifo) in 0.06ms
> 2021-03-03T06:43:59Z 76932 TID-chg ActiveJob/GuestsCleanupJob/cjlarose_shoryuken_test.fifo/8b67661b-8d02-48d1-b88f-f4d6ed5a93ca INFO: completed in: 437.565 ms
> ```
> 
> I think the problem might have been with the way you were enqueuing the message into SQS. Were you using `#perform_later`?

I think i'm just missing specify the :shoryuken adapter in config/application.rb

```
    config.active_job.queue_adapter = :shoryuken
```

workaround to this
```
  -r ./app/jobs
```

`#perform_later` is work
