### ISSUE TITLE
Progammically adding groups and queues with StrictPriority polling strategy?

### ISSUE THREAD

**Issue by hkrdrm** [ruby-shoryuken/shoryuken#618]
Hey @phstc ,

We are switching our project to use aws's ssm param store instead of ENV variables and we initialize params in boot.rb which gets loaded after the shoryuken.yml so to get around this I'm currently trying add groups and queues in our initializer like this

```ruby
Shoryuken.add_group('group3', Shoryuken.options.fetch(:concurrency, 25))
Shoryuken.add_queue($app_config.get('EMERGENCY_QUEUE'), 1, 'group3')
Shoryuken.add_queue($app_config.get('NON_CRITICAL_QUEUE'), 2, 'group3')
```

I'm not sure how I should go about setting the polling_strategy though.  We want to make sure we have StrictPriority on some of our groups, but it looks like add_group is not going to set it.  Could we edit it and pass it in like your doing concurrency and delay?  I may get fork going and attempt this tomorrow. Any help or direction would be much appreciated.

Thanks,

**Comment by hkrdrm** [comment]
Hey this works for me not sure if your interested in merging upstream but it will gets us going for now.

https://github.com/phstc/shoryuken/compare/master...hkrdrm:ms-add-group-polling-strategy

**Comment by phstc** [comment]
Thanks, that makes sense. Can you PR it?

BTW I did something before for SSM https://github.com/phstc/param_store it might be handy for your use case.

**Comment by hkrdrm** [comment]
Thanks, I submitted the PR and will check out your param_store repo.
