### ISSUE TITLE
Lambda Usage

### ISSUE THREAD

**Issue by metaskills** [ruby-shoryuken/shoryuken#621]
Hi! My name is Ken Collins and I am the author of Lamby, a ruby gem to use Rack/Rails on Lambda. I recently finished up some comprehensive documentation on how to use ActiveJob with Lambda & SQS. 

https://lamby.custominktech.com/docs/activejob_and_lambda

The docs focus on using Shoryuken for the ActiveJob integration but leverages Rails in Lambda for event-driven workers vs polling. Thank you for this wonderful gem and I just wanted to share how I was using it. Cheers!

**Comment by phstc** [comment]
Hi @metaskills 

This is a great initiative. Thanks for sharing it ❤️

**Comment by tomharvey** [comment]
Another awesome contribution from @metaskills 

Huge thanks.
