### ISSUE TITLE
DefaultWorkerRegistry#register_worker fails when `Rails.application.eager_load` called multiple times

### ISSUE THREAD

**Issue by phoebetse** [ruby-shoryuken/shoryuken#623]
### Problem
We have recently added `shoryuken` to our application, and are registering one worker to each queue. However, we noticed that this does not interact well with Shoryuken, which we've just added to our application, and we frequently get the following error: 

> Could not register #{clazz} for #{queue}, because #{worker_class} is already registered for this queue, 
> and Shoryuken doesn't support a batchable worker for a queue with multiple workers

We've identified that this is happening because in our local development environment, we are calling `Rails.application.eager_load!` multiple times. When this is called multiple times, it is calling the `shoryuken_options` that are set on our shoryuken jobs, which then calls [register_worker](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L34) multiple times.

We think it would make sense to make a small change to that method so that shoryuken does not error if a worker is being re-registered (vs registering multiple workers).
 
### Proposed solution:
Adding an additional conditional to [default_worker_registry](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L36 ) so that the error occurs only if worker_class != clazz. In other words, we would only fail if we are attempting to register a different worker. Something like:

```ruby
if (worker_class.get_shoryuken_options['batch'] == true || 
   clazz.get_shoryuken_options['batch'] == true) &&
   worker_class != clazz
          fail ArgumentError, "Could not register #{clazz} for #{queue}, "\
...
```

Thoughts? I'm happy to open a PR to make this fix if this makes sense to others!

**Comment by phstc** [comment]
Why are you registering it? Can't you check if it is already registered before trying to register again?

**Comment by phoebetse** [comment]
@phstc hm, my understanding right now is that it's automatically being registered whenever `Rails.application.eager_load!` is called. Here's what we have:

```ruby
# config/initializers/shoryuken.rb
Shoryuken.configure_server do |config|
...
end

Shoryuken.configure_client do |config|
...
end
```

```ruby
# our Shoryuken job
class OurShoryukenJob
  include Shoryuken::Worker
  shoryuken_options(
    ...
  )

  def perform(_)
    ...
  end
end
```

How are you suggesting checking if it's already registered?  somewhere in `OurShoryukenJob` before the `shoryuken_options` line?

**Comment by phoebetse** [comment]
@phstc hi! wanted to rephrase my question- is there a way to use shoryuken's public API to check if a worker is already registered? if so, do you have an example?

**Comment by phoebetse** [comment]
ah, calling`Shoryuken.worker_registry.clear` right before eager loading solves most of this problem!

However, i'm noticing that after eager loading locally, `Shoryuken.options` no longer returns the Shoryuken server configs that were initially set before eager loading (defaults are returned instead). I'm seeing this when adding `puts #{Shoryuken.options}` to `OurShoryukenJob` Any ideas on why that is/how to address that?
