### ISSUE TITLE
Auto-reload Rails in Development

### ISSUE THREAD

**Issue by waynerobinson** [ruby-shoryuken/shoryuken#658]
Hi

I've been using Shoryuken for a long while now, but never really looked into if its possible to auto-reload Rails per request similar to the way the HTTP endpoints reload?

Is this possible with Shoryuken?

Cheers

**Comment by cjlarose** [comment]
There's an open PR that does this (#627), but when I deployed the changes into a production environment, we encountered some memory problems. I've mostly tabled it for now.

That was for Rails 5.x, though, using the classic autoloader. I haven't experimented with Rails 6.x and the zeitwerk autoloader, but I suspect that might be easier to get working.

**Comment by waynerobinson** [comment]
Thanks, I'll take a look. This project is currently Rails 5, but I don't really care about memory usage in dev anyway. If I only need to restart it 10% of the time it would still be an improvement.
