### ISSUE TITLE
Shoryuken worker claims queue does not exist

### ISSUE THREAD

**Issue by coding-bunny** [ruby-shoryuken/shoryuken#670]
Hello,

I hope I can explain this properly, because I'm at a loss as to why the worker in our K8s pod keeps reporting that the queue does not exist. The credentials are set up correctly, as we use the IAM Profile approach in our containers to assign the required role to a pod for AWS access.

This is what's inside the `config/shoryuken.yml`:

```yaml
---
concurrency: 2
pool: 1
delay: 1
queues:
  - <%= ::ENV['SQS_QUEUE_NAME'] %>
```

We've created a Worker inside our `lib/` folder of the Rails application, but we're not using ActiveJob.
Rails has been given an initializer to load the Worker after Rails has been loaded, which should be the case if I understand the documentation correctly, given that it works locally and no errors are thrown:

```
bundle exec shoryuken -R -C config/shoryuken.yml

bundler: failed to load command: shoryuken (/app/vendor/bundle/ruby/2.7.0/bin/shoryuken)
ArgumentError: The specified queue(s) deployment-history-queue do not exist.
Try 'shoryuken sqs create QUEUE-NAME' for creating a queue with default settings
 app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/lib/shoryuken/environment_loader.rb:162:in `validate_queues'
/app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/lib/shoryuken/environment_loader.rb:30:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/lib/shoryuken/runner.rb:39:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/bin/shoryuken:42:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
/app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/bin/shoryuken:53:in `<top (required)>'
/app/vendor/bundle/ruby/2.7.0/bin/shoryuken:23:in `load'
/app/vendor/bundle/ruby/2.7.0/bin/shoryuken:23:in `<top (required)>'
```

But when running it locally, I need to do it like this to make it work:

```
SQS_QUEUE_NAME=deployment-history-queue bundle exec shoryuken -R -C config/shoryuken.yml
```

Because even though I use the `dotenv` gem, the environment variables are not loaded properly by Shoryuken.
It does work when they exist on the OS level, given the fact that the pod reports the correct queue usage.

So I'm trying to understand why the Pod fails with the queue does not exist error.
Checked our Policy and all permisions are there, and the required variables exist.

**Comment by coding-bunny** [comment]
I've actually connected to our web pod, and ran the following:

```
bundle exec shoryuken sqs ls
bundler: failed to load command: shoryuken (/app/vendor/bundle/ruby/2.7.0/bin/shoryuken)
Aws::SQS::Errors::AccessDenied: Access to the resource https://sqs.us-east-1.amazonaws.com/ is denied.
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-core-3.115.0/lib/seahorse/client/request.rb:72:in `send_request'
  /app/vendor/bundle/ruby/2.7.0/gems/aws-sdk-sqs-1.39.0/lib/aws-sdk-sqs/client.rb:1462:in `list_queues'
  /app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/bin/cli/sqs.rb:161:in `ls'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /app/vendor/bundle/ruby/2.7.0/gems/shoryuken-5.2.2/bin/shoryuken:53:in `<top (required)>'
  /app/vendor/bundle/ruby/2.7.0/bin/shoryuken:23:in `load'
  /app/vendor/bundle/ruby/2.7.0/bin/shoryuken:23:in `<top (required)>'
```

I've checked that all AWS config is there for the IAM Profiles, so it seems Shoryuken has an issue connecting properly with this.

**Comment by coding-bunny** [comment]
When using the Aws SDK directly from the same pod using Rails console:

```
app@deployment-history-chalk-5052-webapp-f7cbb969d-kjbzs:/app$ bundle exec rails c
Loading staging environment (Rails 6.1.4)
irb(main):001:0> sqs = ::Aws::SQS::Client.new
=> #<Aws::SQS::Client>
irb(main):002:0> sqs.get_queue_attributes(queue_url: 'https://sqs.us-east-1.amazonaws.com/322902370520/deployment-history-queue', attribute_names: ['All'])
=> #<struct Aws::SQS::Types::GetQueueAttributesResult attributes={"QueueArn"=>"arn:aws:sqs:us-east-1:322902370520:deployment-history-queue", "ApproximateNumberOfMessages"=>"0", "ApproximateNumberOfMessagesNotVisible"=>"0", "ApproximateNumberOfMessagesDelayed"=>"0", "CreatedTimestamp"=>"1624277795", "LastModifiedTimestamp"=>"1625052256", "VisibilityTimeout"=>"30", "MaximumMessageSize"=>"262144", "MessageRetentionPeriod"=>"345600", "DelaySeconds"=>"90", "ReceiveMessageWaitTimeSeconds"=>"10"}>
```

That call wouldn't work without having the correct IAM Profile assigned.
So this for me clearly illustrates a problem with the Shyuroken client/executable.

**Comment by coding-bunny** [comment]
So, interesting discovery:

I switched the code to look for the `SQS_QUEUE_URL` variable first, and then the `SQS_QUEUE_NAME` as fallback, and when using the full URL for the SQS queue, Shoryuken connects fine without any problems.
So when using the just the queue name, the AWS connection seems to be configured differently than when using the complete SQS URL

**Comment by coding-bunny** [comment]
Just ran a complete integration test, and it works with the URL usage flawlessly.
Not sure why the client doesn't get configured properly with just the name.

```
2021-07-08T12:13:47Z 1 TID-ess INFO: Starting
2021-07-08T12:18:15Z 1 TID-rfs QueueSyncWorker/https://sqs.us-east-1.amazonaws.com/322902370520/deployment-history-queue/b76c6922-8ba4-4e79-b16a-1b3c6e9458b1 INFO: started at 2021-07-08 12:18:15 +0000
2021-07-08T12:18:16Z 1 TID-rfs QueueSyncWorker/https://sqs.us-east-1.amazonaws.com/322902370520/deployment-history-queue/b76c6922-8ba4-4e79-b16a-1b3c6e9458b1 INFO: completed in: 293.11231599999996 ms

```

**Comment by cjlarose** [comment]
The relevant code that's trying to get the queue URL from the queue name is here:

https://github.com/ruby-shoryuken/shoryuken/blob/9c822f4c6aab96719aa292b162a25627103abf87/lib/shoryuken/queue.rb#L65-L68

It's possible that the IAM Profile that you're using for your k8s instances has the privilege to read/write to queues, but does not have the privilege to get the queue URL from a queue name. That line of code listed above ends up calling the [`GetQueueUrl`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html) action, which, according to the [SQS permissions docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html) requires the permission `sqs:GetQueueUrl`. This is a distinct permission from `sqs:GetQueueAttributes`, which you demonstrated works just fine in a Rails console.

**Comment by coding-bunny** [comment]
Aha!
I will verify that tomorrow whether the role has that specific permission!

**Comment by coding-bunny** [comment]
Yup, `sqs:GetQueueUrl` was not granted, so going to grant that now on our app, and allow a simpler configuration!
