### ISSUE TITLE
Shoryuken doesn't process all messages fetched from SQS during a shutdown

### ISSUE THREAD

**Issue by nelhefni** [ruby-shoryuken/shoryuken#677]
Hi, we have been facing some issues during the shutdowns of Shoryuken.
During deployments of our application (we use AWS ECS), we always end up with at least one message that stays “in-flight” in SQS
As a consequence, the message is not visible for some time (until the visibility timeout is reached), which delays its consumption.

After investigating, here is the sequence of events that happen during a shutdown:

- Shoryuken sends a fetch query to SQS (normal process, unrelated to the shutdown)
- SQS receives the query, then lock some messages as `not visible`, and sends back the response (let’s call it R)
- The TERM signal arrives on Shoryuken
- Shoryuken::Launcher.stop! is called, triggering the shutdown of the Executor
- From now on, no more new processes can be assigned to the Executor
- The R response from SQS finally comes back, but we can’t process the messages, as the Executor doesn’t accept any new process
- The messages stay not visible for some time on SQS before being retried

It seems related to this issue: https://github.com/ruby-shoryuken/shoryuken/issues/539
Also, we face the same problem whether we use TERM, TSTP, or USR1 signals.
	
We raised a PR with a fix proposal: https://github.com/ruby-shoryuken/shoryuken/pull/676
It refactors the way TSTP and USR1 signals work.

- Shoryuken sends a fetch query to SQS and keeps a flag in the Manager: `dispatching_in_progress`
- SQS receives the query, then lock some messages as `not visible`, and sends back the response (let’s call it R)
- When the TSTP or USR1 signal is received on Shoryuken, as a first step we stop the dispatch loop to prevent any new fetch message to be sent to SQS
- At this stage, the Executor is still accepting any newly assigned process
- In case any Manager has the `dispatching_in_progress` flag, we wait, with a timeout aligned on the long-polling `wait_time_seconds` setting
- The R response from SQS finally comes back, and the Manager assigns some processes to the Executor and eventually removes the `dispatching_in_progress` flag
- We finally can start the shutdown of the Executor

TERM remains untouched because the time needed for the shutdown is potentially increased with this new approach.
If you have any concerns about backward compatibility, and potential impact on Shoryuken users, we could introduce signal USR2, and keep the existing signals untouched

**Comment by cjlarose** [comment]
Thanks for provided a detailed description of the problem. I'll take a look at the PR shortly!

> If you have any concerns about backward compatibility, and potential impact on Shoryuken users, we could introduce signal USR2, and keep the existing signals untouched

That probably won't be necessary. I think the changes you're introducing change the behavior to what most users expect is already the behavior.
