### ISSUE TITLE
Programmatically booting Shoryuken

### ISSUE THREAD

**Issue by LyleDavis** [ruby-shoryuken/shoryuken#680]
We have a need to programmatically launch Shoryuken. This is because we have a number of tasks that should be performed _prior_ to actually launching the Shoryuken bin script. 

More specifically our use-cases are:
* Create our own temporary shoryuken yaml file (we build it dynamically for a number of reasons)
* load our environment variables for the process from elsewhere
* Add our own default middleware + other default shoryuken configurations for our services (this cannot be done as part of the `require` flag because Shoryuken loads the rails code _before_ this is loaded so our workers that are coming from gems duplicate their own `shoryuken_options_hash` before the app can add its own default middlewares). This is due to the `shoryuken_options` class method duplicating the configuration https://github.com/ruby-shoryuken/shoryuken/blob/afa9e7ff1a9f5c678d156b5fb0000abe75c0af7d/lib/shoryuken/worker.rb#L26

Our current solution to loading Shoryuken programmatically is to call `load` on the shoryuken bin script, but this is admittedly a hack - and not an entirely nice one.

Would you be open to a PR that adds another entrypoint into shoryuken for starting it programmatically within other code, so we don't have to call `load` on the Shoryuken bin script?

As far as I can see the only other bit that would need to change would be `Shoryuken::Options#server?`, which would check something else set by both this programmatic launch and the bin script. https://github.com/ruby-shoryuken/shoryuken/blob/afa9e7ff1a9f5c678d156b5fb0000abe75c0af7d/lib/shoryuken/options.rb#L152

**Comment by cjlarose** [comment]
It seems possible to start a `Shoryuken::Runner` instance from a Ruby API already by calling something similar to what the `bin` script does already:

```
$ ./bin/rails runner "require 'shoryuken/runner'; Shoryuken::Runner.instance.run({rails: true})"
Running via Spring preloader in process 22373
2021-10-15T22:47:01Z 22373 TID-ov7ezp82o WARN: No queues supplied
2021-10-15T22:47:01Z 22373 TID-ov7ezp82o INFO: Starting
```

Is there something about that API that makes it incompatible with what you're trying to do?

**Comment by cjlarose** [comment]
Makes sense! I'm open to changes that make it more ergonomic to launch an instance of Shoryuken. I've seen this work well with things like `Puma::Server` and it sounds like you have a good use case for it.

**Comment by lvonk** [comment]
Hi 👋🏼 ,

For anyone still interested, we are starting and stopping shoryuken programmatically in specs so we can for instance use rspec mocks and such. So after a bit of fiddling we use the following setup in RSpec which seems to work:

```ruby
require 'shoryuken/runner'
require_relative 'shoryuken_patches'

let(:stop_error) { Class.new(RuntimeError) }
let(:shoryuken_thread) do
  Thread.new do
    shoryuken = Shoryuken::Runner.instance
    Shoryuken.logger.level = Logger::INFO
    # When Shoryuken::Runner stops the Concurrent::CachedThreadPool also stops. 
    # This is a singleton and remains stopped even if we instantiate a new runner.
    # To 'fix' this we can pass a new launcher_executor each time when we have a new
    # instance of the Shoryuken::Runner.
    Shoryuken.shoryuken_options.launcher_executor = Concurrent::CachedThreadPool.new(
      auto_terminate: true,
      fallback_policy: :abort, # shouldn't matter -- 0 max queue
      name: 'io',
      )
    Shoryuken.shoryuken_options.server_middleware do |chain|
      # Set middlewares if needed
     
    end

    shoryuken.run(
      {
        queues:,
        config_file: './path/to/config/shoryuken.yml',
      },
      )
  rescue stop_error
    puts 'Shoryuken stopping....'
    shoryuken.stop
    puts 'Shoryuken stopped'
  end
end

before :each { shoryuken_thread }

after :each do
  shoryuken_thread.raise(stop_error)
  shoryuken_thread.join  
end
```

`shoryuken_patches.rb`:

```ruby
# Monkeypatch to be able to stop the Shoryuken::Runner
module Shoryuken
  class Runner
    def stop
      @launcher&.stop
    end
  end
end
```
