### ISSUE TITLE
cutting new versions

### ISSUE THREAD

**Issue by LyleDavis** [ruby-shoryuken/shoryuken#685]
Hey there 👋

We’d love to use the new health check stuff in master in our workers. Is there a timescale on when the next version will be released from master?

I’m not really sure what the process is supposed to be for it, whether bumping versions and tags for rubygems etc is something you do as the maintainer or whether we should be putting up PRs that do it. 

Thanks
Lyle

**Comment by cjlarose** [comment]
[Shoryuken version 5.3.0 is available now on RubyGems](https://rubygems.org/gems/shoryuken/versions/5.3.0)

Usually I cut and release versions pretty quickly after stuff gets merged. Just forgot about it this time around. I appreciate the reminder, though!
