### ISSUE TITLE
Breaks Sidekiq Enterprise preload

### ISSUE THREAD

**Issue by patbenatar** [ruby-shoryuken/shoryuken#690]
See https://github.com/mperham/sidekiq/issues/4766#issuecomment-990419555

**Comment by patbenatar** [comment]
🤷‍♂️

**Comment by matt-taylor** [comment]
Hey @patbenatar 
Are you still running into this issue? If so can you give some more details:
- Shoryuken config
- Sidekiq Swarm start command
- How you include the Shoryuken gem in your Gemfile
- Any other details that can help us reproduce this issue

Thanks

**Comment by patbenatar** [comment]
@matt-taylor We've worked around the issue by updating our `gem "rails"` line in the Gemfile to explicitly require the libs we want. That seems to be the generally accepted solution on the Sidekiq issues thread when you have a gem that causes the problem (like these ones that suffer from the same issue as Shoryuken https://github.com/mperham/sidekiq/issues/4766#issuecomment-749094226)

Our shoryuken.yml:

```
concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 25) %>
delay: <%= ENV.fetch("SQS_DELAY", 30) %>
```

Gemfile:

```
gem "shoryuken", "~> 5.3.2"
```

sidekiqswarm launch:

```
SIDEKIQ_PRELOAD_APP=1 bundle exec sidekiqswarm
```

I would assume you can repro with a vanilla Rails app including both shoryuken and sidekiqswarm, but I haven't tried to create a repro app like that.

**Comment by matt-taylor** [comment]
Unfortunately, I am unable to reproduce this with the following:
- new rails 6.1.x application
- shoryuken 5.2.3
- sidekiq  6.4.1
- sidekiq ent 2.2.2

I would assume that there is some custom configuration that has been done with rails. Would you be able to shed some light into what your configuration looks like when this was failing?
- What railsy frameworks are included in the gemfile and in the application config
- What bundler group is shoryuken/rails/sidekiq included in?

**Comment by patbenatar** [comment]
@matt-taylor Thanks for looking into this. We're no longer using sidekiqswarm so I'm not able to attempt a repro on latest Shoryuken in our app to help diagnose. I'll go ahead and close this out.
