### ISSUE TITLE
Push version 6.0.0 to Rubygems?

### ISSUE THREAD

**Issue by undergroundwebdesigns** [ruby-shoryuken/shoryuken#697]
Hello!

It looks like a version 6.0.0 has been published here several days ago, but isn't available on RubyGems, is that intentional? Are there plans to publish this version at some point, or is there some bug or issue blocking it from being published?

I'm interested in using some of the features of the new version but am a bit confused about its release status.

Cheers!

**Comment by cjlarose** [comment]
There was an issue running the tests on JRuby on 6.0.0, so I didn't publish it right away. I'll take a look

**Comment by phstc** [comment]
@undergroundwebdesigns 6.0.0 is out https://rubygems.org/gems/shoryuken/versions/1.0.2

thanks @cjlarose for the awesome work!
