### ISSUE TITLE
Hi,  i need to understand few line of code in Shoryuken::Processor perform method

### ISSUE THREAD

**Issue by GiriCredAvenue** [ruby-shoryuken/shoryuken#703]
Hi can someone explain the below lines of code in the Shoryuken::Processor perform method, I am new to ruby and rails, so I am finding it difficult to understand. 

Mainly I can't able to understand middleware part, whether it invokes the `call` method of all Shoryuken middleware, if yes, then whether middleware are executed before or after doing the **worker.perform** method?

```
Shoryuken::Logging.with_context("#{worker_name(worker.class, sqs_msg, body)}/#{queue}/#{sqs_msg.message_id}") do
        worker.class.server_middleware.invoke(worker, queue, sqs_msg, body) do
          worker.perform(sqs_msg, body)
        end
end
```

My doubt is 
1. Whether Shoryuken initiates a delete request to SQS queue even if workers perform methods throw exceptions?

**Comment by matt-taylor** [comment]
Hey @GiriCredAvenue.

The deletion of a sqs message happens via middleware. You can see the order of the middleware here https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/options.rb#L165-L176

You can see how each middleware behaves here: https://github.com/ruby-shoryuken/shoryuken/tree/v6.0.0/lib/shoryuken/middleware/server


---
> My doubt is
Whether Shoryuken initiates a delete request to SQS queue even if workers perform methods throw exceptions?

If a worker raises an error during execution, the expectation is that the sqs message **does not get deleted** but rather the message gets retried. Take a look at the documentation here https://github.com/ruby-shoryuken/shoryuken/wiki/Retrying-a-message.


Hope that helps
