### ISSUE TITLE
Enable batching for active jobs.

### ISSUE THREAD

**Issue by jibin-k-jose** [ruby-shoryuken/shoryuken#710]
Hi Guys. As part of reducing SQS costs for our shoruken implemetation, we would like to know if it is possible to enbale batching for AtiveJob. I see that the shoryuken workers have the batch option. Is an equivalent option available for Active Jobs as well?

**Comment by matt-taylor** [comment]
Hey @jibin-k-jose. Apologies for the delay. 

[ActiveJobs purpose](https://edgeguides.rubyonrails.org/active_job_basics.html#the-purpose-of-active-job) is as follows:
> The main point is to ensure that all Rails apps will have a job infrastructure in place. We can then have framework features and other gems build on top of that, without having to worry about API differences between various job runners such as Delayed Job and Resque. Picking your queuing backend becomes more of an operational concern, then. And you'll be able to switch between them without having to rewrite your jobs.

What this means is that all adapters should respond the same API's regardless of which adapter is used. Adding a custom option or method for the Shoryuken Active Job Adapter to allow Job classes to retrieve multiple messages would go against this principle and cause a rift between other adapters.
(Other adapters do the same. EG: Sidekiq custom options are not available on its active job adapter)

If you need additional custom support for batching, I would suggest using raw Shoryuken Worker and its options avaialbe via `shoryuken_options`

**Comment by jibin-k-jose** [comment]
Thank you, @matt-taylor

**Comment by baxang** [comment]
Active Job introduced `#perform_all_later` by using the queue adapter's `#enqueue_all` and the built-in Sidekiq adapter implements it: [code](https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L35-L64)

Could this be reconsidered?

**Comment by phstc** [comment]
Hi @baxang 

Since it's available on Active Job, that can be reconsidered. One point of attention is that SQS batches a maximum of ten at a time. The implementation would need to take this into consideration.

We would also need to figure out how to limit it only to Rails 7 (the one that supports `perform_all_later`). 

Would you like to work on a PR?
