### ISSUE TITLE
Map messages to a worker

### ISSUE THREAD

**Issue by coding-bunny** [ruby-shoryuken/shoryuken#712]
Hello,

our problem is something similar to https://github.com/ruby-shoryuken/shoryuken/issues/688
We are currently experimenting with the AWS EventBridge that pushes messages on the SQS Queue, and we would like a single worker to actually pick up those messages and process them.

However since we do not control the events/messages, we ofcourse do not have the `shoryuken_class` field set on these messages, as it's not ActiveJob that's creating or pushing these messages.

Does Shoryken have a possibility to somehow tell it, accept this message, regardless of where it comes from?

**Comment by phstc** [comment]
You could try a non-ActiveJob worker. 

https://github.com/ruby-shoryuken/shoryuken/wiki/Worker-options

That can be mapped to a queue regarderless the `shoryuken_class` value.
