### ISSUE TITLE
Two workers on seperate instances, CPU usage imbalance

### ISSUE THREAD

**Issue by ameyerfr** [ruby-shoryuken/shoryuken#714]
Hello,

I have this setup : a simple Rails app with a Shoruyken worker (polling from several queues, with the batch option activated)

There is the same code on two separate EC2 instances on AWS, and the machines only runs the Shoryuken process.

There is a significant imbalance of CPU, one instance is at 50% whereas the other at 2%.

The 2% machine still consumes messages, so its working but there seems to be a mechanism that prevents it to have the same load as the other machine, as i expected it to.

Any clues regarding a configuration or something i did not consider?

Thanks

**Comment by phstc** [comment]
Are you using a delay?

https://github.com/ruby-shoryuken/shoryuken/wiki/Shoryuken-options#delay

If your volume is low or inconsistent, there's the possibility that one instance is consuming all messages while the other is continuously getting delayed.

**Comment by ameyerfr** [comment]
@phstc I am not using delay (neither on the SQS config)

There is a fair bit of volume (1k messages / hour), an there is only very small windows with no messages

![Capture d’écran 2022-09-27 à 11 29 55](https://user-images.githubusercontent.com/129462/192489640-d51e0dc1-2ca2-4eda-9ac6-9e6b2e76b916.png)

**Comment by phstc** [comment]
What's the concurrency you have configured? If you are using 25 or more, it could explain one instance getting all messages based on your graph distribution.

**Comment by ameyerfr** [comment]
@phstc The concurrency in the shoryuken config file is set to 1, however i have somewhere between 8 to 10 process. I tried other values for concurrency and that seems to do nothing. Could that be a pointer to another issue?

What it looks like is that one of the process crash or something like that and then it goes up to 100% cpu, why makes the cpu of the machine very high (around 50%) compared to the average normal (around 3%)

**Comment by phstc** [comment]
> however i have somewhere between 8 to 10 process

messages to process? If so, with concurrency 1, it would process one at a time per Shoryuken instance. Or do you have 8-10 Shoryuken instances?

**Comment by ameyerfr** [comment]
No, sorry, i have 8-10 Shoryuken instances on the machine even tho i have 1 as concurrency. I have way more messages than that (1k messages / hour see above) and they are handled with the batch option
