### ISSUE TITLE
Different Worker directories for Shoryuken and Sidekiq

### ISSUE THREAD

**Issue by vipulvkp** [ruby-shoryuken/shoryuken#715]
I have a rails app where we want to use both sidekiq (redis queue) and shoryuken (sqs queue) for different use cases. So now , all the sidekiq workers are defined under `app/workers`. To separate out shoryuken workers, we thought to define and keep then under `app/consumers`.

So we are running this command to start shoryuken

```
shoryuken -r ./app/consumers/ -R -C ./config/shoryuken.yml
```

my question is , does giving the -r options with worker directory path forces shoryuken to load workers from that path, as we want to keep separate directories for sidekiq workers (app/workers) and shoryuken workers (app/consumers)

**Comment by matt-taylor** [comment]
Hey @vipulvkp 

Yes `-r` option is the option to use  input the location of your Shoryuken Workers if they are in an unexpected location. If `-r` is given a directory, Shoryuken will load all `.rb` files under that directory. If `-r` is given a file path, Shoryuken will load that single file. 

Here is the source: https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/environment_loader.rb#L139-L149

**Comment by vipulvkp** [comment]
Thank you so much @matt-taylor .
Closing this issue

**Comment by vipulvkp** [comment]
@matt-taylor actually there was another observation.
So I start shoryuken as below
```
shoryuken -r app/consumers/ -R -C ./config/shoryuken.yml
```

Please note: its "app/consumers",  not "./app/consumers". 

The above command fails with the error
`LoadError: cannot load such file -- app/consumers/my_consumer.rb`

But if I give "./app/consumers"., its able to load properly.

This may be because we are using `require` to load files instead of using require_relative

Just a small observation!
Thank you
