### ISSUE TITLE
No worker found error when running moto/fakesqs

### ISSUE THREAD

**Issue by shawnwonolo** [ruby-shoryuken/shoryuken#717]
I've tried running both moto and fakesqs, but I keep getting a `No worker found` error when I try to run a job on a queue other than default. Default queue works fine.

I'm using ActiveJob in rails. So, I'm running MyJob.perform_later() when I get the error. Here are the logs:
```
2022-11-03T23:33:49Z 1 TID-x9am0t5kc INFO: Starting
2022-11-03T23:34:55Z 1 TID-x9amfhi10 ERROR: No worker found for otherqueue
```

Other information about my setup that may or may not be relevant:

I'm running all the stuff in docker.

I'm booting up shoryuken with command: ["bundle", "exec", "shoryuken", "--rails", "--delay", "1", "--timeout", "40", "--concurrency", "2", "-r", "./app/jobs", "-q", "otherqueue"]. I'm using `-r` based on what was recommended/what I saw in the wiki, but that didn't fix the issue.

I'm creating the queue with a ruby script. sqs client is set up with
```
Aws::SQS::Client.new(
    region: 'us-west-2',
    access_key_id: 'none',
    secret_access_key: 'none',
    endpoint: 'http://fakesqs:4576',
    verify_checksums: false
  )
```

I have `active_job_queue_name_prefixing` set to `true`, but prefix is set to an empty string. I did fiddle with it a little bit and I don't think it's causing the issue, but haven't confirmed.

I think I'm setting up the queues correctly because otherwise shoryuken doesn't boot and gives different errors.

Running shoryuken 6.0.0 and aws-sdk-core 3.131.1

I can repro on with the Rails repo I'm running, but haven't yet tried it on a more minimal rails setup.

**Comment by hex337** [comment]
Any chance you can try giving an absolute path for the `-r` command instead of a relative one?

**Comment by shawnwonolo** [comment]
Tried the absolute path, still getting the same error.

**Comment by matt-taylor** [comment]
Hey @shawnwonolo 

Can you give more details about what the ActiveJob is and if it has `otherqueue` as the queue set?
Also, What is the non-prod value of `Shoryuken.worker_registry` return to you?

**Comment by nbulaj** [comment]
The same actually with LocalStack, haven't resolved yet
