### ISSUE TITLE
ActiveSupport::CurrentAttributes parameters resetting after being set in server middleware

### ISSUE THREAD

**Issue by saksham-jain** [ruby-shoryuken/shoryuken#719]
- I am using Shoryuken for ActiveJob.
- Using ActiveSupport::CurrentAttributes to store **firm_name** in a multi-tenant application. This firm_name is coming from the SQS message attribute and is stored in CurrentAttributes to keep it available through the job processing. 
This flow works fine with sidekiq. But with the Shoryuken, after **firm_name** is set in middleware, the ActiveSupport reloader runs which resets all CurrentAttributes. 
- This issue was strange until I look into Sidekiq's process method(in processor.rb). Sidekiq runs the reloader before the server_middlewares, whereas with Shoryuken reloader runs after server_middlewares. 

**Sidekiq process method-**
```
dispatch(job_hash, queue, jobstr) do |inst|    # ----> this dispatch method runs reloader
   config.server_middleware.invoke(inst, job_hash, queue) do 
      execute_job(inst, job_hash["args"]) 
   end
end

#reloader running before server_middleware
```

**Shoryuken process method-**
```
Shoryuken::Logging.with_context("#{worker_name(worker.class, sqs_msg, body)}/#{queue}/#{sqs_msg.message_id}") do
   worker.class.server_middleware.invoke(worker, queue, sqs_msg, body) do
      worker.perform(sqs_msg, body) # ----> this ultimately calls active job which has reloader callback
   end
end

#reloader running after server_middleware
```

- The proposed fix is to introduce a reloader around server_middleware in Shoryuken similar to Sidekiq. Like this-
```
::Rails.application.reloader.wrap do  # ----> run reloader before server_middleware
  Shoryuken::Logging.with_context("#{worker_name(worker.class, sqs_msg, body)}/#{queue}/#{sqs_msg.message_id}") do
    worker.class.server_middleware.invoke(worker, queue, sqs_msg, body) do
        worker.perform(sqs_msg, body) 
    end
  end
end
```

- This fixes the issue and ActiveSupport::CurrentAttributes doesn't reset after being set in server_middleware

**Comment by matt-taylor** [comment]
Hi @saksham-jain 

Thanks for the detail here. One thing to note is that Shoryuken (And Sidekiq) can be used without rails so we would need to be cognizant of that for any change that gets made.

---

I'm looking into reproducing this issue but in the meantime, but can you give a little more insight into your exact job and any callbacks that might be made? FWIW, Shoryuken does not do anything specific in regards to reloading. Active Support is indirectly called when Active Job loads its perform method which may contribute to your issue.

**Comment by saksham-jain** [comment]
@matt-taylor Thanks for responding.
Okay, we might need to see to make it framework agnostic.

Yes, I agree ActiveJob does reloading in my case, when I do reloading in the Shoryuken's process method reloading doesn't happen with ActiveJob. I don't expect reloading after middleware.  So this solves my problem. 

As per sidekiq([Reference](https://github.com/mperham/sidekiq/blob/e64e359c906cfc56bee8a6e17df686aec5e3bc7d/lib/sidekiq/processor.rb#L134)) reloader block denotes a "unit of work" to Rails.
