### ISSUE TITLE
Rails Reloading Support for Development Environment

### ISSUE THREAD

**Issue by littleali** [ruby-shoryuken/shoryuken#720]
Hi,
I am using `Shoryuken` in a Rails app. 
Because it doesn't support autoreload, it means for any change that I make on shoryuken-related code, I should restart the Shoryuken manually and also because everything else is having autoreload in the development environment, I should be aware of which changes need to restart the Shoryuken, so having the autoreload feature in development improves productivity and decreases errors during development. 

I've read both #627 and #658, and It seems there were some memory problems with #627 in the production environment, I'm confused about it as @cjlarose himself suggest to disable autoreload on production using `config.cache_classes = true`.

I tried the solution on #627 and it works properly in the development environment. Is it possible to have this feature just for the development environment? 

Thank you in Advance.

**Comment by matt-taylor** [comment]
Hi @littleali Apologies for the delay here.

Reloading was talked about in a recent issue https://github.com/ruby-shoryuken/shoryuken/issues/719. Seems like Reloading can be useful for the Shoryuken community.

----

I do not fully understand what sort of Memory issues occurred in #627 for it to get abandoned, but it seems like a good starting point. Looks like you are already starting on the work with https://github.com/certsy/shoryuken/pull/1. 
Please reach out if you need any help

Some things to be careful of:
- Spring can cause issues with App relaoder and `cache_classes` Rails option
- Rails is not a guarantee when using Shoryuken. This means the reloader will not be available all the time

**Comment by littleali** [comment]
@matt-taylor, thank you for your response, 
I don't know what memory problem happened in #627 either. 
So we are testing on our staging/production and see if there are any memory-related problems, and then we submit a new PR.

**Comment by littleali** [comment]
@matt-taylor 
After testing the Rails reloader-enabled version with no problem for more than 2 months, I created a new PR (#725) to add this feature to the Shoryuken.
