### ISSUE TITLE
Question about max_number_of_messages and concurrency

### ISSUE THREAD

**Issue by alexlopes** [ruby-shoryuken/shoryuken#723]
Hello everyone! First of all, congrats for the project :clap: 

Now I have a basic question about concurrency and `max_number_of_messages`. According to [this line](https://github.com/ruby-shoryuken/shoryuken/blob/main/lib/shoryuken/fetcher.rb#L73) I can't have the concurrency value below the default `max_number_of_messages` value. 

```ruby
      [limit, FETCH_LIMIT, options[:max_number_of_messages]].compact.min
```
For instance, If I want a `concurrency=2` and `max_number_of_messages=10` (2 threads fetching 10 messages) is not possible because the min will return 2 for the max_number_of_messages.

The number of threads should follow this logic? Sorry if I am asking something too newbie but I got confused. Can you explain how it works?

**Comment by matt-taylor** [comment]
Hey @alexlopes welcome 👋🏾 

For some context, `max_number_of_messages` is used to help reduce AWS usage cost by polling in batches. 

Shoryuken concurrency is measured differently than the `max_number_of_messages`. Shoryuken concurrency is the max number of jobs that can be processed concurrently after those jobs have been pulled from SQS. Whereas `max_number_of_messages` config option is the max number of messages that can be returned at a single time.

Shoryuken will use  `max_number_of_messages` to fetch as many messages it can and then pass each message to a new concurrent thread.

https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/manager.rb#L111-L115

Hope that helps

**Comment by alexlopes** [comment]
Hi @matt-taylor ! Thank you very much for replying me! Got it, but I still have a question regarding the  `max_number_of_messages` calculation.
  
As you pointed, we have the sequence `dispatch_single_messages > fetch > receive_messages > max_number_of_messages`.  

As I see, the `max_number_of_messages` value relies on this logic 

```ruby
[limit, FETCH_LIMIT, options[:max_number_of_messages]].compact.min
```
During my tests, I noticed that `limit` has the same value of `concurrency`. So if I have `concurrency=2` (2 jobs), `max_number_of_messages` has the same value(2), because of `min` logic. I realized this behavior watching [this log](https://github.com/ruby-shoryuken/shoryuken/blob/3afa2b655482f9dc97d5538964fa4b9b6f1506ef/lib/shoryuken/fetcher.rb#L19) during the execution.

What I am trying to say is, can I have a hypothetical scenario where `concurrency=2` and `max_number_of_messages=10` ?

**Comment by matt-taylor** [comment]
Can you confirm that there are more than 2 messages in the AWS SQS when you try to fetch the message?

----

But yes you can have concurrency 2 and max_number_of_messages 10. What this will give you is the following:

- At most 10 messages fetched from SQS (Less messages if there are not 10 messages)
- Concurrency of 2 jobs processed at a time.

**Comment by alexlopes** [comment]
Hi @matt-taylor, yes, I did some tests producing between 100 to 3000 messages. 

I realized that the [max_number_of_messages](https://github.com/ruby-shoryuken/shoryuken/blob/main/lib/shoryuken/fetcher.rb#L73) always returns the value from `concurrency` (when this value is below 10). 

Do you think am I doing something wrong during the setup? 

**config/initializers/shoryuken.rb**
```ruby
Shoryuken.sqs_client_receive_message_opts = {
  max_number_of_messages: 10
}
```

**config/shoryuken.yml**
```yaml
concurrency: 2
queues:
  - <%= ENV['SQS_APP_QUEUE'] %>
```

**exec**
```console
bundle exec shoryuken -v -R -C ./config/shoryuken.yml -r ./app/jobs/
```

**logs***
`about 200 messages in the AWS SQS queue`
```console
Firing 'utilization_update' lifecycle event
Found 2 messages for notifications-test-queue
Fetcher for notifications-test-queue completed in 320.490763 ms
Assigning 08aa07c9-cf07-4f1f-9b38-9d1d657477c8
```

**Comment by matt-taylor** [comment]
Thanks for that information @alexlopes. I think I misunderstood or missed part of your question.

As you stated before, it will take the min of 
```ruby
[limit, FETCH_LIMIT, options[:max_number_of_messages]].compact.min
```

The relationship to the concurrency of the process and this number is directly related for single messages.

----

The variable [ready](https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/manager.rb#L76-L78) at [this line](https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/manager.rb#L112) represents the number of available threads that can be used. 

In your example, this `ready` number will be 2 (unless a thread is currently occupied). The default concurrency for Shoryuken is 25 as [referenced here](https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/options.rb#L4). This means that for default processes that does not modify the concurrency, the `ready` variable can be as high as 25.

---

You are not doing anything wrong in your config here as this is the design. The goal being to never take more messages than can be concurrently processed.

**Comment by alexlopes** [comment]
Hi @matt-taylor ! Perfect, I am glad to know my config is correct and my walkthrough as well. The design makes total sense, thank you very much for your attention and explanation :) .
