### ISSUE TITLE
Load balancing vs the default pooling strategy documentation

### ISSUE THREAD

**Issue by springerigor** [ruby-shoryuken/shoryuken#726]
Is [the documentation about load balancing](https://github.com/ruby-shoryuken/shoryuken/wiki/Shoryuken-options#load-balancing) still valid? It is contrary to what the documentation says about [the default polling strategy says](https://github.com/ruby-shoryuken/shoryuken/wiki/Polling-strategies#weightedroundrobin) and the order of queues processing.

The Load balancing documentation suggests that when there are three queues with `8`, `4` and `1` weights defined:
```yml
queues:
  - [queue1, 8]
  - [queue2, 4]
  - [queue3, 1]
```
the first one will be checked for new messages 8 times before checking the second one. The default polling strategy documentation says something different.

**Comment by matt-taylor** [comment]
Hi @springerigor 

The documentation on the [LoadBalancing](https://github.com/ruby-shoryuken/shoryuken/wiki/Shoryuken-options#load-balancing) is accurate. The documentation on [Default polling strategy](https://github.com/ruby-shoryuken/shoryuken/wiki/Polling-strategies#weightedroundrobin) is incorrect. 

The code will pull 8 times from queue1 before it pulls 4 times from queue2. 

Shoryuken uses `shift` to get the next queue. Under normal circumstances*, this will cause queue1 to get polled 8 times before an attempt on queue2 is polled. 
https://github.com/ruby-shoryuken/shoryuken/blob/v6.0.0/lib/shoryuken/polling/weighted_round_robin.rb#L13

### What are normal circumstances?
Normal circumstances mean the queue is never fully drained. When the queue is drained, the order in which items get polled **will change** in a nondeterministic way. Can get more into these details if you would like

----

I will take a stab at updating the documentation on [the default polling strategy](https://github.com/ruby-shoryuken/shoryuken/wiki/Polling-strategies#weightedroundrobin) soonish.

Thanks for pointing out the discrepency
