### ISSUE TITLE
Add Support for Non-retryable Exception to Shoyuken

### ISSUE THREAD

**Issue by pyueli** [ruby-shoryuken/shoryuken#734]
I am working on Shoyuken recently and found the default [exponential_backoff_retry](https://github.com/ruby-shoryuken/shoryuken/blob/main/lib/shoryuken/middleware/server/exponential_backoff_retry.rb) middleware doesn't support non-retryable Exception. It will retry the failed message multiple times with intervals specified by [retry_intervals](https://github.com/ruby-shoryuken/shoryuken/blob/f24db5422ef6869c4a556c134a27b4259027e7b8/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L33). One idea is to add a new non_retryable_exception middleware, which allows user specify the list of non-retryable exceptions in the worker. This new middleware can be added after the exponential_backoff_retry middleware. 

Below is the pseudo code.
```
    def call(worker, _queue, sqs_msg, _body)
      yield
    rescue => ex
       if ex in nonretryable_exceptions
          sqs_msg.delete
          logger.warn ...
          return
       end 
       raise
```
I am happy to work on a PR to solve this issue.
Below are two sequence diagrams showing how the new middleware handles the worker exceptions based on the exception type.
Any thoughts? Thx!
<img width="756" alt="Screenshot 2023-05-09 at 11 28 05 AM" src="https://github.com/ruby-shoryuken/shoryuken/assets/10213168/335c0a28-eda5-4309-950f-af33452bf401">
<img width="760" alt="Screenshot 2023-05-09 at 11 28 18 AM" src="https://github.com/ruby-shoryuken/shoryuken/assets/10213168/c30814a4-2167-43f8-b69a-3ac4292aaf29">

**Comment by phstc** [comment]
Hi @pyueli 

Do you have many workers that you want to silently ignore errors? If it's a one-off case, I would recommend the approach you suggested. 

```ruby
class Worker
  include Shoryuken::Worker

  shoryuken_options retry_intervals: [300, 1200, 3600] # 5.minutes, 20.minutes and 1.hour

  def perform(sqs_msg, name)
    # do something
  rescue SomeError => ex
    # ignore some error
  end
end
```

How are you thinking about adding it to `retry_intervals`? Your example is not ignoring exponential backoff. It is removing the message (silencing the error)

**Comment by pyueli** [comment]
Hi @phstc 
Thanks for your reply. Yes. There are multiple cases for this requirment. So I am trying to build this feature as a new middleware in Shoryuken instead of duplicating the exception handling login in the worker.
