### ISSUE TITLE
When in Rails mode, in development environment, does not load app/workers automatically

### ISSUE THREAD

**Issue by ayqazi** [ruby-shoryuken/shoryuken#743]
I'm running a Rails app and am running Shoryuken worker as part of it. In development mode, it outputs "No worker found for qq" when I start it. It seems to work fine in production mode because Rails loads all classes at startup anyway.

I have a worker in app/workers with:
```
  shoryuken_options queue: 'qq', auto_delete: true
```

My config file in config/shoryuken.yml:
```
concurrency: 1
pidfile: ./tmp/shoryuken.pid
queues:
  - 'qq'
```

I start with: `bundle exec shoryuken --rails -C ./config/shoryuken.yml` and add some items to the queue.

Output:

```
[2023-09-18 16:17:51] ERROR: No worker found for domain-events
```

Now I restart with `bundle exec shoryuken --rails -r worker_class -C ./config/shoryuken.yml`

Suddenly I start getting logging messages saying the worker has consumed messages.

I thought `--rails` automatically loaded everything in `app/workers`?

**Comment by josebalius** [comment]
@ayqazi did you ever figure out why this happens?

**Comment by ayqazi** [comment]
No sorry, have moved on from the job now.

Regards,
    Asfand
