### ISSUE TITLE
SIGTERM does not stop dispatching of new messages from the queue

### ISSUE THREAD

**Issue by hoffi** [ruby-shoryuken/shoryuken#749]
After sending `SIGTERM` to Shoryuken, messages are still fetched from SQS.

I have found [`Launcher#stop!`](https://github.com/ruby-shoryuken/shoryuken/blob/main/lib/shoryuken/launcher.rb#L16), which does not stop the dispatching other than `Launcher#stop`.
I am not sure why. Doesn't it make sense to also stop the dispatching in this case?

When running the Shoryuken Worker on AWS ECS there is always a `SIGTERM` when the ECS task is stopping and waits up to 30 seconds by default until it is force killed: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-lifecycle.html#lifecycle-states.
So i cannot use the `SIGUSR1` signal.

**Comment by phstc** [comment]
@hoffi would `executor.kill` called there automatically stop the dispatch?

**Comment by hoffi** [comment]
but would cause the processing of messages already started before the signal to be force stopped?
That is not necessary in that case as we still have 30 seconds to finish the processes already started before to finish. But it shouldn‘t fetch new messages in that time when it already knows that it is about to shutdown

**Comment by phstc** [comment]
I don't remember any reason for not calling `stop_new_dispatching` on `stop!`. 

Do you want to PR a change? I can 👀
