### ISSUE TITLE
Exception in Shoryuken::Queue#receive_messages

### ISSUE THREAD

**Issue by mkeemon** [ruby-shoryuken/shoryuken#752]
Last night, we saw our Shoryuken processes begin to fail with the below error. It appears that the `aws-ruby-sdk` SQS client's `receive_message` function is sometimes returning an empty array and sometimes returning `nil`. It's unclear if this is a change in the `aws-sdk` gem behavior or the AWS APIs. My guess would be the latter since this happened overnight in between releases to our application.

```
Shoryuken -- Manager failed: undefined method `map' for nil:NilClass
.../shoryuken-6.1.0/lib/shoryuken/queue.rb:46:in `receive_messages'
```

We've monkey patched this in our application for the time being:

```rb
module Shoryuken
  class Queue
    def receive_messages(options)
      messages = client.receive_message(options.merge(queue_url: url)).messages || []
      messages.map { |m| Message.new(client, self, m) }
    end
  end
end
```

**Comment by phstc** [comment]
Hi @mkeemon 

That's unexpected. I would guess something on the AWS side. 

Would you be able to submit a PR with the failsafe change?

**Comment by jsteinberg** [comment]
We saw the same issue also start last night.  There is some explanation in this issue here:

https://github.com/aws/aws-sdk-ruby/issues/2947

**Comment by mkeemon** [comment]
All set @phstc  https://github.com/ruby-shoryuken/shoryuken/pull/753. Let me know if you need anything else or if I did something improperly!
