### ISSUE TITLE
Support for ActiveJob.perform_all_later (Rails 7.1)

### ISSUE THREAD

**Issue by gondalez** [ruby-shoryuken/shoryuken#761]
Hi, 

Thanks for the handy gem 😌 🙏 
We have been using it for ActiveJob mainly and it has been useful for our production workload.

I stumbled on `ActiveJob.perform_all_later` that was [added in rails 7.1](https://www.bigbinary.com/blog/rails-7-1-adds-activejob-perform-all-later).

Are there any plans to support it in `shoryuken`?
We have our own janky implementation of batch enqueueing that we would love to remove, should it become an implementation detail of `shoryuken` 😌 

Specifically to support creating many sqs message in a single [`SendMessageBatch`](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html) for increased throughput.

The rails PR for reference: https://github.com/rails/rails/pull/46603

There is an existing old closed issue, #710, but per this [comment](https://github.com/ruby-shoryuken/shoryuken/issues/710#issuecomment-1791860350), it predates rails 7.1 which lead to it being closed.
 
I figured I'd open a new issue for clarity and extra visibility.

**Comment by phstc** [comment]
Hi @gondalez 

There's no work being done related to that. All current improvements are individual-driven. 

Are you interested in submitting a PR?

**Comment by gondalez** [comment]
@phstc no worries, I totally understand 👍 

I don't have any spare time to do the change at the moment.
But if you're happy to I think it'd be good to leave the PR open in case some kind traveller wants to have a try? :)

I figure this issue is also handy as a "not yet supported" doc for anyone searching.
