### ISSUE TITLE
`aws-sdk-core` 3.194.x breaks Shoryuken

### ISSUE THREAD

**Issue by arvinwiyono** [ruby-shoryuken/shoryuken#767]
Dear Shoryuken team,

I am reporting here that the latest versions of `aws-sdk-core` (`3.194.2`) break Shoryuken when used with Rails ActiveJob. Messages enqueued to SQS queue do not get consumed by the worker and straight away go to the DLQ. I cannot find any error messages produced by the Shoryuken worker either.

More details about my broken setup:
- `aws-sdk-sqs` (`1.64.0`)
- `aws-sdk-core` (`3.194.2`)
- `aws-partitions` (`1.926.0`)
- `shoryuken` (`6.2.1`)
- `activejob` (`7.1.3.2`)
- `rails` (`7.1.3.2`)

**Comment by arvinwiyono** [comment]
Update: Upgrading `aws-sdk-sqs` from 1.64.0 to 1.73.0 solves this issue.

**Comment by jakswa** [comment]
Wild that shoryuken just keeps chugging silently with no errors as payloads end up in the DLQ. I believe we ran into this today in production -- thank you for reporting this, we'll see if updating SQS (and maybe shoryuken too) fixes this.

**Comment by DavidMealha-Onfido** [comment]
Plus one, the same happened to us after upgrading Rails 7.0 to 7.2, which required a bump of Shoryuken from 6.0 to 6.2 due to a [bug regarding deprecation notices for Rails 7.1+ version](https://github.com/ruby-shoryuken/shoryuken/commit/66850164f4237772157232b0b352be8a69c15fc1).

After the updates above all the SQS messages were received but not deleted. Upgrading aws-sdk-sqs fixed the issue.

**Comment by arinhouck** [comment]
There seems like a larger issue that should be opened up (maybe there is?), the fact that shoryuken doesn't produce a runtime error and just silently fails / doesn't consume message. The company I work at just had our DLQ loaded up but ZERO logs to help clarify the source of the error.

Would love some confidence that we can assure issues like this will at least raise a runtime error?

Does anyone have more insights on the how to observe or capture these dependency mismatches other than observing DLQ and being completely confused?

**Comment by mensfeld** [comment]
If the issue still exists in 7.0.0.alpha2 please open a new issue
